#version: "3.8"

networks:
    inception-network:
        driver: bridge

services:
    wordpress:
        depends_on:
            - mariadb
        container_name: my_wordpress
        build: ./requirements/wordpress
        image: wordpress
        volumes:
            - wordpress_volume:/var/www/wordpress
        networks:
            - inception-network
        restart: always
        environment:
            - WORDPRESS_DB_NAME
            - WORDPRESS_DB_USER
            - WORDPRESS_DB_PASSWORD
        expose:
            - "9000"

    nginx:
        depends_on:
            - wordpress
        container_name: my_nginx
        build: ./requirements/nginx
        image: nginx
        volumes:
            - wordpress_volume:/var/www/wordpress
        networks:
                - inception-network
        restart: always
        environment:
            - NGINX_WORDPRESS_CONTAINER_NAME
            - NGINX_WORDPRESS_PORT
        ports:
            - "443:443"
        extra_hosts:
            - "fmeira.42.fr:127.0.0.1"
            - "www.fmeira.42.fr:127.0.0.1"

    mariadb:
        container_name: my_mariadb
        build: ./requirements/mariadb
        volumes:
            - wordpress_volume:/var/lib/mysql
        networks:
            - inception-network
        environment:
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
        image: mariadb
        restart: always

volumes:
        wordpress_volume:
                driver: local
                driver_opts:
                        device: /home/user/data/wordpress-volume
                        o: bind
                        type: none
        wordpress_volume:
                driver: local
                driver_opts:
                        device: /home/user/data/mariadb
                        o: bind
                        type: none
