version: "3.8"

networks:
    localhost:
        name: inet

services:
    nginx:
        depends_on:
            - wordpress
        container_name: my_nginx
        build: requirements/nginx
        image: nginx
        volumes:
            - wordpress:/var/www/wordpress
        networks:
                - localhost
        restart: always
        environment:
            - NGINX_WORDPRESS_CONTAINER_NAME
            - NGINX_WORDPRESS_PORT
        ports:
            - "443:443"
    wordpress:
        depends_on:
            -mariadb
        container_name: my_wordpress
        build: requirements/wordpress
        image: wordpress
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - localhost
        restart: always
        environment:
            - WORDPRESS_DB_NAME
            - WORDPRESS_DB_USER
            - WORDPRESS_DB_PASSWORD

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/fmeira/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/fmeira/data/mariadb
                        o: bind
                        type: none
