version: "3.8"

services:
    mariadb:
        build: requirements/mariadb
        container_name: mariadb
        env_file: ./.env
        image: mariadb
        networks:
            - inception_network
        expose:
            - "3306"
        volumes:
          - mariadb_volume:/var/lib/mysql
        extra_hosts:
            - "fmeira.42.fr:0.0.0.0"
            - "www.fmeira.42.fr:0.0.0.0"
        restart: always

    wordpress:
        build: requirements/wordpress
        container_name: wordpress
        env_file: ./.env
        image: wordpress
        depends_on:
            - mariadb
        networks:
            - inception_network
        volumes:
            - wordpress_volume:/var/www/html
        restart: always
        extra_hosts:
            - "fmeira.42.fr:0.0.0.0"
            - "www.fmeira.42.fr:0.0.0.0"
        expose:
            - "9000"

    nginx:
        build: requirements/nginx
        container_name: nginx
        env_file: ./.env
        image: nginx
        depends_on:
            - wordpress
        networks:
            - inception_network
        ports:
            - "443:443"
        volumes:
            - wordpress_volume:/var/www/html
            - ./nginx_logs:/var/log/nginx/
        restart: always
        extra_hosts:
        - "fmeira.42.fr:0.0.0.0"
        - "www.fmeira.42.fr:0.0.0.0"

networks:
    inception_network:
        driver: bridge

volumes:
        mariadb_volume:
                driver: local
                driver_opts:
                        device: /home/user/data/mariadb_volume
                        o: bind
                        type: none
        wordpress_volume:
                driver: local
                driver_opts:
                        device: /home/user/data/wordpress_volume
                        o: bind
                        type: none
